// Autogenerated from Pigeon (v10.1.6), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class BridgeLeanplumUserAttributes;

/// This is is only for generating pigeon code, never import this file.
@interface BridgeLeanplumUserAttributes : NSObject
+ (instancetype)makeWithEmail:(nullable NSString *)email
    userId:(nullable NSString *)userId;
@property(nonatomic, copy, nullable) NSString * email;
@property(nonatomic, copy, nullable) NSString * userId;
@end

/// The codec used by BridgeLeanplumNativeMethod.
NSObject<FlutterMessageCodec> *BridgeLeanplumNativeMethodGetCodec(void);

@protocol BridgeLeanplumNativeMethod
- (void)initAppId:(NSString *)appId appKey:(NSString *)appKey error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setUserAttributesAttributes:(BridgeLeanplumUserAttributes *)attributes error:(FlutterError *_Nullable *_Nonnull)error;
- (void)trackEventName:(NSString *)eventName params:(nullable NSDictionary<NSString *, id> *)params error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void BridgeLeanplumNativeMethodSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<BridgeLeanplumNativeMethod> *_Nullable api);

/// The codec used by BridgeLeanplumMsgCallbacks.
NSObject<FlutterMessageCodec> *BridgeLeanplumMsgCallbacksGetCodec(void);

@interface BridgeLeanplumMsgCallbacks : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
@end

NS_ASSUME_NONNULL_END
