// Autogenerated from Pigeon (v10.1.6), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

/// This is is only for generating pigeon code, never import this file.
class BridgeLeanplumUserAttributes {
  BridgeLeanplumUserAttributes({
    this.email,
    this.userId,
  });

  String? email;

  String? userId;

  Object encode() {
    return <Object?>[
      email,
      userId,
    ];
  }

  static BridgeLeanplumUserAttributes decode(Object result) {
    result as List<Object?>;
    return BridgeLeanplumUserAttributes(
      email: result[0] as String?,
      userId: result[1] as String?,
    );
  }
}

class _BridgeLeanplumNativeMethodCodec extends StandardMessageCodec {
  const _BridgeLeanplumNativeMethodCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is BridgeLeanplumUserAttributes) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return BridgeLeanplumUserAttributes.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class BridgeLeanplumNativeMethod {
  /// Constructor for [BridgeLeanplumNativeMethod].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  BridgeLeanplumNativeMethod({BinaryMessenger? binaryMessenger})
      : _binaryMessenger = binaryMessenger;
  final BinaryMessenger? _binaryMessenger;

  static const MessageCodec<Object?> codec = _BridgeLeanplumNativeMethodCodec();

  Future<void> init(String arg_appId, String arg_appKey) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.channeltalk.BridgeLeanplumNativeMethod.init', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_appId, arg_appKey]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> setUserAttributes(BridgeLeanplumUserAttributes arg_attributes) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.channeltalk.BridgeLeanplumNativeMethod.setUserAttributes', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_attributes]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> track(String arg_eventName, Map<String?, Object?>? arg_params) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.channeltalk.BridgeLeanplumNativeMethod.track', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_eventName, arg_params]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }
}

abstract class BridgeLeanplumMsgCallbacks {
  static const MessageCodec<Object?> codec = StandardMessageCodec();

  static void setup(BridgeLeanplumMsgCallbacks? api, {BinaryMessenger? binaryMessenger}) {
  }
}
